# Generated by Django 3.0.4 on 2020-03-08 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tim_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_public', models.TimeField()),
                ('due_date', models.TimeField()),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=10)),
                ('concepts', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.BooleanField()),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('parent_thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_thread_id', to='main.Comment')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Comment')),
                ('responding_to', models.ManyToManyField(related_name='comment_responding_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
