# Generated by Django 3.0.4 on 2020-03-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200308_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='categories',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='concepts',
            field=models.CharField(max_length=100),
        ),
    ]
