# Generated by Django 3.0.4 on 2020-03-08 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200308_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='tim_created',
            new_name='time_created',
        ),
        migrations.AlterField(
            model_name='pdf',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='time_public',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
